### PR TITLE
Write openqcd format

### PR DESCRIPTION
**Pull request by RJaBi**
This is a pull-request to add the ability to save gaugefields in openqcd file format

- Adds a re-ordering routine from the internal representation to openqcd
- Adds a function to calculate the average plaquette
   - This is required for the openqcd header
   - This code is not at all optimised.
- Implements (non-parallel) saving of openqcd format
   - writes header and binary to file

The tests I have done are involved reading in an openqcd format gaugefield, writing it, reading it again and doing measurements on each
- Calculated spatial and temporal plaquettes
   - This is a test of the re-ordering of space versus time. Notably it does not test that any of the three spatial indices are not mis-ordered with each other.
- Examined a handful of individual sites and checked they were the same.

I'm not entirely sure how the Dask or MPI IO work as I have no used them and hence they are explicitly disabled via a `NotImplementedError`

### CODE REVIEW

**Comment by sbacchio** [comment]
Thanks a lot! Looks good, but I would suggest implementing the plaquette also as a c function.
Loops over data using Python are highly inefficient. The calculation of the plaquette might end up taking a huge time depending on the lattice size. Would you mind adding such implementation in the openqcd.h file?

**Comment by sbacchio** [comment]
an alternative would be to use numba (https://numba.pydata.org/) to compile the python code. Would you be conformatble with that? It should be as simple as `@njit` before the function since loops are already explicit.

**Comment by RJaBi** [comment]
That's good to hear.

I had a quick play around with numba without success, but I feel that just doing it in C is a better option anyway. 

[Ben Page](https://github.com/jadot-bp) and I have C-code to do the plaquette, so we will look at copying it across soon hopefully.

**Comment by jadot-bp** [comment]
The latest changes to the `write_openqcd` branch include updates to both `openqcd.py` and `openqcd.h` to support faster plaquette calculation for the OpenQCD header. Please let us know if you require any additional changes.

**Comment by sbacchio** [comment]
Thanks, looks great! I will merge it in `develop`  and in the next few days make it part of the release. 
I would add to the author list Ryan Bignell and Ben Page. Anyone else that has contributed?
Cheers!

**Comment by jadot-bp** [comment]
Excellent! We were glad to help. Thank you for adding us both to the author list. There are no other contributors for this branch.

**Comment by RJaBi** [comment]
> Thanks, looks great! I will merge it in `develop`  and in the next few days make it part of the release. 
> I would add to the author list Ryan Bignell and Ben Page. Anyone else that has contributed?
> Cheers!

That's it.

Many thanks Simone. I have to thank Ben heaps for picking this up too.

**Pull request merged**
